export const teamMembers = [
  {
    name: "Nikita Clark",
    title: "Founder & President",
    photo: "/team/nikita_main.webp",
    legend: "/team/nikita-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/nikitaclark315/",
    bio: "Former software developer and founder of multiple startups. Graduated from Northeastern University and scaled his first company to $1M ARR while still in college. Combines hands-on technical skill with sharp business execution to build and grow high-performing software ventures.",
  },
  {
    name: "Kabir Israni",
    title: "Strategic Partner & Advisor",
    photo: "/team/kabir_main.webp",
    legend: "/team/kabir-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/kabirisrani/",
    bio: "Founder and CEO of Raveum, a global real estate investment platform. With a strong background in fintech and proptech, Kabir leads teams building compliant, scalable systems. At Junzi, he provides strategic guidance on growth, capital, and partnerships.",
  },
  {
    name: "Ayush Shenvi Pissurlenkar",
    title: "Technical Advisor",
    photo: "/team/ayush_main.webp",
    legend: "/team/ayush-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/ayush-shenvipissurlenkar/",
    bio: "Co-founder and CTO of a real estate technology company scaled to a $50M valuation. Northeastern University graduate with proven ability to design and lead complex engineering systems. Brings deep technical expertise and product vision to JunziTech.",
  },
  {
    name: "Anton Vinogradov",
    title: "Lead Engineer & System Architect",
    photo: "/team/anton_main.webp",
    legend: "/team/anton-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/vinogradovanton/",
    bio: "Experienced technologist and software architect with a strong background in large-scale systems and AI-driven solutions. At Junzi, Anton leads engineering strategy and architecture, ensuring every product is built with precision, performance, and long-term scalability in mind.",
  },
  {
    name: "Muhammad Haris",
    title: "Head Of Design",
    photo: "/team/haris_main.webp",
    legend: "/team/haris-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/muhammadharys/",
    bio: "UI/UX and product designer with over six years specializing in web and mobile design. Expert in turning complex ideas into intuitive, conversion-focused interfaces. At Junzi, Muhammad leads product design and user experience with a focus on performance.",
  },
] as const;
